<a href="https://colab.research.google.com/github/edolubis/Advanced-Wrangling/blob/main/wrangling_data_sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

## 1. Loading Sales Data

In [ ]:
## Loading Data & Directory sesuaikan dengan komputer masing-masing

df_product_dataset = pd.read_csv('Documents/LAB-BI2/Data Sales/olist_products_dataset.csv')
df_customer_dataset = pd.read_csv('Documents/LAB-BI2/Data Sales/olist_customers_dataset.csv')
df_order_item_dataset = pd.read_csv('Documents/LAB-BI2/Data Sales/olist_order_items_dataset.csv')
df_order_review_dataset = pd.read_csv('Documents/LAB-BI2/Data Sales/olist_order_reviews_dataset.csv')
df_orders_dataset = pd.read_csv('Documents/LAB-BI2/Data Sales/olist_orders_dataset.csv')
df_sellers_dataset = pd.read_csv('Documents/LAB-BI2/Data Sales/olist_sellers_dataset.csv')

## 2. Merging Every Sales Data

In [ ]:
dfmerged1 = pd.merge(df_order_review_dataset,df_orders_dataset, how='inner')
dfmerged2 = pd.merge(df_order_item_dataset,dfmerged1,how='inner')
dfmerged3 = pd.merge(dfmerged2,df_product_dataset, how='inner')
dfmerged4 = pd.merge(dfmerged3,df_sellers_dataset, how='inner')
dfmerged5 = pd.merge(dfmerged4,df_customer_dataset, how='inner')
dfmerged5

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,review_id,review_score,review_comment_title,...,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29,97ca439bc427b48bc1cd7177abe71365,5,NaN,...,28.0,9.0,14.0,27277,volta redonda,SP,871766c5855e863f6eccc05f988b23cb,28013,campos dos goytacazes,RJ
1,130898c0987d1801452a8ed92a670612,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-07-05 02:44:11,55.9,17.96,b11cba360bbe71410c291b764753d37f,5,NaN,...,28.0,9.0,14.0,27277,volta redonda,SP,0fb8e3eab2d3e79d92bb3fffbb97f188,75800,jatai,GO
2,532ed5e14e24ae1f0d735b91524b98b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2018-05-23 10:56:25,64.9,18.33,af01c4017c5ab46df6cc810e069e654a,4,super recomendo,...,28.0,9.0,14.0,27277,volta redonda,SP,3419052c8c6b45daf79c1e426f9e9bcb,30720,belo horizonte,MG
3,6f8c31653edb8c83e1a739408b5ff750,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-07 18:55:08,58.9,16.17,8304ff37d8b16b57086fa283fe0c44f8,5,NaN,...,28.0,9.0,14.0,27277,volta redonda,SP,e7c828d22c0682c1565252deefbe334d,83070,sao jose dos pinhais,PR
4,7d19f4ef4d04461989632411b7e588b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-16 22:05:11,58.9,13.29,426f43a82185969503fb3c86241a9535,5,NaN,...,28.0,9.0,14.0,27277,volta redonda,SP,0bb98ba72dcc08e95f9d8cc434e9a2cc,36400,conselheiro lafaiete,MG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112367,fecc4ea5a3e06ce3192ae2f05b7a8439,2,70adb75b3b2e86cffbb697c90867c3f3,4e2627090e6e5b9fabba883a37897683,2018-01-21 22:09:08,39.9,14.10,ad39f464785acf795ee836cb3472756e,1,NaN,...,65.0,11.0,11.0,31565,belo horizonte,MG,12bf6178776d90da204cdf1b37d23906,13214,jundiai,SP
112368,fecc4ea5a3e06ce3192ae2f05b7a8439,3,70adb75b3b2e86cffbb697c90867c3f3,4e2627090e6e5b9fabba883a37897683,2018-01-21 22:09:08,39.9,14.10,ad39f464785acf795ee836cb3472756e,1,NaN,...,65.0,11.0,11.0,31565,belo horizonte,MG,12bf6178776d90da204cdf1b37d23906,13214,jundiai,SP
112369,fecc4ea5a3e06ce3192ae2f05b7a8439,4,70adb75b3b2e86cffbb697c90867c3f3,4e2627090e6e5b9fabba883a37897683,2018-01-21 22:09:08,39.9,14.10,ad39f464785acf795ee836cb3472756e,1,NaN,...,65.0,11.0,11.0,31565,belo horizonte,MG,12bf6178776d90da204cdf1b37d23906,13214,jundiai,SP
112370,ff701a7c869ad21de22a6994237c8a00,1,5ff4076c0f01eeba4f728c9e3fa2653c,3e35a8bb43569389d3cebef0ce820f69,2018-04-18 20:10:33,27.9,14.44,2926f21f2f2aba2ce11d801e17eac783,5,NaN,...,19.0,38.0,19.0,3124,sao paulo,SP,ddb2249e0316d365ceae561c0f011bce,12280,cacapava,SP
112371,ff701a7c869ad21de22a6994237c8a00,2,5ff4076c0f01eeba4f728c9e3fa2653c,3e35a8bb43569389d3cebef0ce820f69,2018-04-18 20:10:33,27.9,14.44,2926f21f2f2aba2ce11d801e17eac783,5,NaN,...,19.0,38.0,19.0,3124,sao paulo,SP,ddb2249e0316d365ceae561c0f011bce,12280,cacapava,SP

## 3. Check and Drop Null Value

In [ ]:
dfmerged5.isna().sum()

order_id                             0
order_item_id                        0
product_id                           0
seller_id                            0
shipping_limit_date                  0
price                                0
freight_value                        0
review_id                            0
review_score                         0
review_comment_title             98938
review_comment_message           64730
review_creation_date                 0
review_answer_timestamp              0
customer_id                          0
order_status                         0
order_purchase_timestamp             0
order_approved_at                   15
order_delivered_carrier_date      1184
order_delivered_customer_date     2360
order_estimated_delivery_date        0
product_category_name             1598
product_name_lenght               1598
product_description_lenght        1598
product_photos_qty                1598
product_weight_g                    18
product_length_cm                   18
product_height_cm                   18
product_width_cm                    18
seller_zip_code_prefix               0
seller_city                          0
seller_state                         0
customer_unique_id                   0
customer_zip_code_prefix             0
customer_city                        0
customer_state                       0
dtype: int64

In [ ]:
total_na = dfmerged5.isnull().sum().sort_values(ascending=False)
percent = ((dfmerged5.isnull().sum()/dfmerged5.isnull().count())*100).sort_values(ascending=False)
na_data = pd.concat([total_na,percent], axis=1,keys=['Total_NA','Percent_%'])

na_data

                               Total_NA  Percent_%
review_comment_title              98938  88.045065
review_comment_message            64730  57.603318
order_delivered_customer_date      2360   2.100167
product_category_name              1598   1.422062
product_photos_qty                 1598   1.422062
product_description_lenght         1598   1.422062
product_name_lenght                1598   1.422062
order_delivered_carrier_date       1184   1.053643
product_width_cm                     18   0.016018
product_height_cm                    18   0.016018
product_length_cm                    18   0.016018
product_weight_g                     18   0.016018
order_approved_at                    15   0.013349
customer_zip_code_prefix              0   0.000000
customer_unique_id                    0   0.000000
seller_state                          0   0.000000
seller_city                           0   0.000000
seller_zip_code_prefix                0   0.000000
customer_city                         0   0.000000
order_id                              0   0.000000
order_estimated_delivery_date         0   0.000000
order_item_id                         0   0.000000
order_purchase_timestamp              0   0.000000
order_status                          0   0.000000
customer_id                           0   0.000000
review_answer_timestamp               0   0.000000
review_creation_date                  0   0.000000
review_score                          0   0.000000
review_id                             0   0.000000
freight_value                         0   0.000000
price                                 0   0.000000
shipping_limit_date                   0   0.000000
seller_id                             0   0.000000
product_id                            0   0.000000
customer_state                        0   0.000000

### Karena Column "review_comment_title" dan "review_comment_message" memiliki file N/A lebih dari 50%, maka tidak didrop melainkan diisi sesuai rating yang diberikan pembeli

# Fill N/A pada column 'review_comment_title' dan 'review_comment_message' karena file N/A >50%

In [ ]:
## Isi komentar sesuai dengan rating score yang diberikan Pembeli

dfmerged5.loc[(dfmerged5.review_score == 5),'review_comment_title'] = dfmerged5['review_comment_title'].fillna('Maravilhoso')
dfmerged5.loc[(dfmerged5.review_score == 4),'review_comment_title'] = dfmerged5['review_comment_title'].fillna('Muito bom')
dfmerged5.loc[(dfmerged5.review_score == 3),'review_comment_title'] = dfmerged5['review_comment_title'].fillna('poderia ser melhor')
dfmerged5.loc[(dfmerged5.review_score == 2),'review_comment_title'] = dfmerged5['review_comment_title'].fillna('estou desapontado')
dfmerged5.loc[(dfmerged5.review_score == 1),'review_comment_title'] = dfmerged5['review_comment_title'].fillna('Muito desapontado')


dfmerged5.loc[(dfmerged5.review_score == 5),'review_comment_message'] = dfmerged5['review_comment_message'].fillna('Perfeito')
dfmerged5.loc[(dfmerged5.review_score == 4),'review_comment_message'] = dfmerged5['review_comment_message'].fillna('Muito bom')
dfmerged5.loc[(dfmerged5.review_score == 3),'review_comment_message'] = dfmerged5['review_comment_message'].fillna('poderia ser melhor')
dfmerged5.loc[(dfmerged5.review_score == 2),'review_comment_message'] = dfmerged5['review_comment_message'].fillna('estou desapontado')
dfmerged5.loc[(dfmerged5.review_score == 1),'review_comment_message'] = dfmerged5['review_comment_message'].fillna('Muito desapontado')

## Cek %  Data N/A

In [ ]:
total_na = dfmerged5.isnull().sum().sort_values(ascending=False)
percent = ((dfmerged5.isnull().sum()/dfmerged5.isnull().count())*100).sort_values(ascending=False)
na_data = pd.concat([total_na,percent], axis=1,keys=['Total_NA','Percent_%'])

na_data

                               Total_NA  Percent_%
order_delivered_customer_date      2360   2.100167
product_category_name              1598   1.422062
product_name_lenght                1598   1.422062
product_description_lenght         1598   1.422062
product_photos_qty                 1598   1.422062
order_delivered_carrier_date       1184   1.053643
product_weight_g                     18   0.016018
product_length_cm                    18   0.016018
product_height_cm                    18   0.016018
product_width_cm                     18   0.016018
order_approved_at                    15   0.013349
seller_zip_code_prefix                0   0.000000
seller_city                           0   0.000000
seller_state                          0   0.000000
customer_unique_id                    0   0.000000
customer_zip_code_prefix              0   0.000000
customer_city                         0   0.000000
order_estimated_delivery_date         0   0.000000
order_id                              0   0.000000
order_item_id                         0   0.000000
order_purchase_timestamp              0   0.000000
order_status                          0   0.000000
customer_id                           0   0.000000
review_answer_timestamp               0   0.000000
review_creation_date                  0   0.000000
review_comment_message                0   0.000000
review_comment_title                  0   0.000000
review_score                          0   0.000000
review_id                             0   0.000000
freight_value                         0   0.000000
price                                 0   0.000000
shipping_limit_date                   0   0.000000
seller_id                             0   0.000000
product_id                            0   0.000000
customer_state                        0   0.000000

## Dropna dan Cek Kembali jumlah N/A pada dataset

In [ ]:
dfmerged5.dropna(axis=0, inplace = True)

In [ ]:
dfmerged5.isna().sum()

order_id                         0
order_item_id                    0
product_id                       0
seller_id                        0
shipping_limit_date              0
price                            0
freight_value                    0
review_id                        0
review_score                     0
review_comment_title             0
review_comment_message           0
review_creation_date             0
review_answer_timestamp          0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
product_category_name            0
product_name_lenght              0
product_description_lenght       0
product_photos_qty               0
product_weight_g                 0
product_length_cm                0
product_height_cm                0
product_width_cm                 0
seller_zip_code_prefix           0
seller_city                      0
seller_state                     0
customer_unique_id               0
customer_zip_code_prefix         0
customer_city                    0
customer_state                   0
dtype: int64

## Reset Index

In [ ]:
dfmerged5.reset_index(inplace=True)

## 4. Convert Incorrect Columns' Format to Corrected Format

In [ ]:
dfmerged5.dtypes

index                              int64
order_id                          object
order_item_id                      int64
product_id                        object
seller_id                         object
shipping_limit_date               object
price                            float64
freight_value                    float64
review_id                         object
review_score                       int64
review_comment_title              object
review_comment_message            object
review_creation_date              object
review_answer_timestamp           object
customer_id                       object
order_status                      object
order_purchase_timestamp          object
order_approved_at                 object
order_delivered_carrier_date      object
order_delivered_customer_date     object
order_estimated_delivery_date     object
product_category_name             object
product_name_lenght              float64
product_description_lenght       float64
product_photos_qty               float64
product_weight_g                 float64
product_length_cm                float64
product_height_cm                float64
product_width_cm                 float64
seller_zip_code_prefix             int64
seller_city                       object
seller_state                      object
customer_unique_id                object
customer_zip_code_prefix           int64
customer_city                     object
customer_state                    object
dtype: object

In [ ]:
dfmerged5['order_delivered_carrier_date'] = pd.to_datetime(dfmerged5['order_delivered_carrier_date'])
dfmerged5['order_delivered_customer_date'] = pd.to_datetime(dfmerged5['order_delivered_customer_date'])
dfmerged5['shipping_limit_date'] = pd.to_datetime(dfmerged5['shipping_limit_date'])
dfmerged5['order_purchase_timestamp'] = pd.to_datetime(dfmerged5['order_purchase_timestamp'])
dfmerged5['order_approved_at'] = pd.to_datetime(dfmerged5['order_approved_at'])
dfmerged5['order_estimated_delivery_date'] = pd.to_datetime(dfmerged5['order_estimated_delivery_date'])
dfmerged5['review_answer_timestamp'] = pd.to_datetime(dfmerged5['review_answer_timestamp'])
dfmerged5['review_creation_date'] = pd.to_datetime(dfmerged5['review_creation_date'])


## 5. Convert bahasa di category name yang masih dalam Bahasa Portugis ke dalam Bahasa Inggris.

In [ ]:
list(dfmerged5['product_category_name'].unique())

['cool_stuff',
 'brinquedos',
 'tablets_impressao_imagem',
 'pet_shop',
 'moveis_decoracao',
 'cama_mesa_banho',
 'perfumaria',
 'informatica_acessorios',
 'utilidades_domesticas',
 'papelaria',
 'ferramentas_jardim',
 'esporte_lazer',
 'telefonia',
 'audio',
 'beleza_saude',
 'bebes',
 'construcao_ferramentas_jardim',
 'relogios_presentes',
 'livros_tecnicos',
 'dvds_blu_ray',
 'consoles_games',
 'alimentos',
 'fashion_bolsas_e_acessorios',
 'casa_conforto',
 'moveis_sala',
 'casa_conforto_2',
 'instrumentos_musicais',
 'automotivo',
 'moveis_escritorio',
 'casa_construcao',
 'construcao_ferramentas_iluminacao',
 'eletronicos',
 'sinalizacao_e_seguranca',
 'cine_foto',
 'construcao_ferramentas_construcao',
 'telefonia_fixa',
 'fraldas_higiene',
 'pc_gamer',
 'fashion_roupa_masculina',
 'eletroportateis',
 'industria_comercio_e_negocios',
 'construcao_ferramentas_seguranca',
 'fashion_esporte',
 'malas_acessorios',
 'market_place',
 'construcao_ferramentas_ferramentas',
 'eletrodomesticos',
 'agro_industria_e_comercio',
 'climatizacao',
 'artes',
 'la_cuisine',
 'portateis_casa_forno_e_cafe',
 'moveis_cozinha_area_de_servico_jantar_e_jardim',
 'livros_interesse_geral',
 'eletrodomesticos_2',
 'alimentos_bebidas',
 'musica',
 'moveis_quarto',
 'bebidas',
 'artigos_de_natal',
 'artigos_de_festas',
 'moveis_colchao_e_estofado',
 'cds_dvds_musicais',
 'seguros_e_servicos',
 'fashion_roupa_infanto_juvenil',
 'fashion_roupa_feminina',
 'pcs',
 'fashion_underwear_e_moda_praia',
 'fashion_calcados',
 'livros_importados',
 'artes_e_artesanato',
 'flores',
 'portateis_cozinha_e_preparadores_de_alimentos']

In [ ]:
dfmerged5 = dfmerged5.replace({'product_category_name'


                               :{'cama_mesa_banho':'Bedding_And_Bath',
                                 'perfumaria':'Perfumery',
                                 'audio':'Electronics',
                              'telefonia':'Telephone',
                              'utilidades_domesticas':'Housewares',
                              'beleza_saude':'Beauty_Health',
                              'bebes':'Babies_and_Toys',
                              'brinquedos':'Babies_and_Toys',
                              'livros_tecnicos':'Books',
                              'alimentos':'Foods_And_Beverages',
                              'fashion_bolsas_e_acessorios':'Bag_Accessories',
                              'casa_conforto':'Home_Comfort',
                              'moveis_sala':'living_room_furniture',
                              'casa_conforto_2':'Home_Comfort',
                              'moveis_escritorio':'office_furniture',
                              'moveis_decoracao':'furniture_decoration',
                              'ferramentas_jardim':'garden_tools',
                              'casa_construcao':'house_construction',
                              'sinalizacao_e_seguranca':'signaling_and_security',
                              'construcao_ferramentas_iluminacao':'construction_tools_lighting',
                              'esporte_lazer':'Sport_Leisure',
                              'papelaria':'Stationary',
                              'consoles_games':'Electronics',
                              'informatica_acessorios':'Pcs',
                              'construcao_ferramentas_construcao':'Construction_Tools',
                              'cine_foto':'Photography_Equipments',
                              'fraldas_higiene':'hygiene_diapers',
                              'fashion_roupa_masculina':'fashion_men_clothing',
                              'automotivo':'automotive',
                              'relogios_presentes':'gifts_watches',
                              'construcao_ferramentas_seguranca':'construction_tools_security',
                              'agro_industria_e_comercio':'agro industry_and_commerce',
                              'eletronicos':'Electronics',
                              'climatizacao':'air conditioning',
                              'instrumentos_musicais':'Music_Instruments',
                              'construcao_ferramentas_ferramentas':'Construction_Tools',
                              'malas_acessorios':'Bag_Accessories',
                              'livros_interesse_geral':'Books',
                              'industria_comercio_e_negocios':'industry_commerce_and_business',
                              'moveis_cozinha_area_de_servico_jantar_e_jardim':'Kitchen_And_Outdoor_Furniture',
                              'artes':'Art',
                              'musica':'song',
                              'moveis_quarto':'bedroom_furniture',
                              'eletrodomesticos':'home_appliances',
                              'artigos_de_festas':'party_supplies',
                              'construcao_ferramentas_jardim':'construction garden tools',
                              'cds_dvds_musicais':'Musics_CDs_And_Dvds',
                              'eletroportateis':'small_appliances',
                              'eletrodomesticos_2':'home_appliances',
                              'portateis_casa_forno_e_cafe':'Kitchen_And_Food_Processor',
                              'telefonia_fixa':'Telephone',
                              'pcs':'Pcs',
                              'bebidas':'Foods_And_Beverages',
                              'alimentos_bebidas':'Foods_And_Beverages',
                              'dvds_blu_ray':'Musics_CDs_And_Dvds',
                              'fashion_calcados':'fashion_shoes',
                              'market_place':'Market_place',
                              'artes_e_artesanato':'arts_crafts',
                              'fashion_underwear_e_moda_praia':'fashion_underwear_beachwear',
                              'tablets_impressao_imagem':'Electronic_Tablets',
                              'fashion_roupa_infanto_juvenil':'Children_Youth_Clothes',
                              'portateis_cozinha_e_preparadores_de_alimentos':'Food_Processor',
                              'livros_importados':'Books',
                              'artigos_de_natal':'Christmas_Accessories',
                              'flores':'Flowers'},

                              })

## Jumlah Total Pembelian Customer

In [ ]:
dfmerged5['Total'] = dfmerged5['price'] * dfmerged5['order_item_id']

In [ ]:
dfmerged5[['customer_unique_id', 'Total']].groupby(dfmerged5['customer_state']).sum().sort_values(['Total'], ascending=False)

                     Total
customer_state
SP              5677757.12
RJ              1978785.13
MG              1711160.39
RS               817513.65
PR               757203.82
SC               559284.13
BA               554678.47
DF               325023.58
GO               319748.95
ES               289452.91
PE               264775.91
CE               243821.98
MT               178845.83
PA               176182.69
MA               127585.77
MS               127556.00
PB               119865.75
PI                94410.04
RN                86122.39
AL                82846.01
SE                60964.29
TO                51910.04
RO                47698.84
AM                23821.20
AC                17854.86
AP                15437.58
RR                 7682.40

## Seller yang paling banyak menjual produk

In [ ]:
dfmerged5['product_id'].groupby(dfmerged5['seller_id']).count().sort_values(ascending=False)

seller_id
6560211a19b47992c3666cc44a7e94c0    1985
4a3ca9315b744ce9f8e9374361493884    1949
1f50f920176fa81dab994f9023523100    1927
cc419e0650a3c5ba77189a1882b7556a    1755
da8622b14eb17ae2831f4ac5b9dab84a    1565
                                    ...
63191ead8d3b2f937cd1996fdcbbad20       1
630008e0f062605a415d694489f6f82e       1
d2572f31e9023e9850ef986a636ff9bf       1
62de60d81c55c29d76a6bce418b31cef       1
7cf4ea70955b00d6b3c22542598e2715       1
Name: product_id, Length: 2909, dtype: int64

## Rename File

# PR (bisa di Tableau)
## 1. Mulai kelompokkan produk dengan rating bagus dan buruk.
## 2. Buat persentase kelompok barang yang delivery dan tidak, cek masalah distribusi tiap region.
## 3. Cek penjualan tiap kota, cek yang banyak menghasilkan sales dan yang kurang.
## 4. Customer unique ID yang banyak melakukan pembelian.